CREATE EXTENSION IF NOT EXISTS citext;
CREATE EXTENSION IF NOT EXISTS hstore;
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS postgis; 

-- IF YOU WANT UNIT TESTS, INSTALL PGTAP AND ENABLE THE FOLLOWING LINE 
CREATE EXTENSION IF NOT EXISTS pgtap;
