BEGIN;
\i Extensions/extensions.sql;
\i Schemas_Tables/raw.sql; 
\i Schemas_Tables/apiv2.sql; 
\i Functions/raw_functions.sql;
\i Triggers/raw_triggers.sql;
\i Functions/apiv2_functions.sql;
\i Triggers/apiv2_triggers.sql;
\i Data/user_data.sql;
\i Data/location_data.sql;
\i Data/trips_inf.sql;
\i Data/triplegs_inf.sql;
\i Data/travel_mode.sql; 
\i Data/purposes.sql;
\i Data/pois.sql;
\i Data/pois_transportation.sql;
COMMIT;
